# Generated by Django 3.2.6 on 2021-09-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author_img', models.ImageField(upload_to='media')),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('study_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('current_year', models.CharField(blank=True, max_length=50, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=500)),
                ('react', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_reply', models.CharField(max_length=500)),
                ('comment_time_created', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.author')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='media')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('react', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.author')),
                ('comment', models.ManyToManyField(to='blogs.Comment')),
            ],
        ),
    ]
