# Generated by Django 3.2.7 on 2021-10-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_img',
            field=models.ImageField(default='images/default_user.png', upload_to='media'),
        ),
    ]
